// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v4.22.2
// source: goshare/others.proto

package goshare

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetInAmountDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount     float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Percentage float64 `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
}

func (x *NetInAmountDetail) Reset() {
	*x = NetInAmountDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goshare_others_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetInAmountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetInAmountDetail) ProtoMessage() {}

func (x *NetInAmountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_goshare_others_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetInAmountDetail.ProtoReflect.Descriptor instead.
func (*NetInAmountDetail) Descriptor() ([]byte, []int) {
	return file_goshare_others_proto_rawDescGZIP(), []int{0}
}

func (x *NetInAmountDetail) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NetInAmountDetail) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type RealtimeMoneyTrendItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol             string             `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name               string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price              float64            `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	UpdownPercentage   float64            `protobuf:"fixed64,4,opt,name=updown_percentage,json=updownPercentage,proto3" json:"updown_percentage,omitempty"`
	Time               int64              `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	SuperSuperBigOrder *NetInAmountDetail `protobuf:"bytes,7,opt,name=super_super_big_order,json=superSuperBigOrder,proto3" json:"super_super_big_order,omitempty"` // 主力净流入
	SuperBigOrder      *NetInAmountDetail `protobuf:"bytes,8,opt,name=super_big_order,json=superBigOrder,proto3" json:"super_big_order,omitempty"`                  // 超大单净流入
	BigOrder           *NetInAmountDetail `protobuf:"bytes,9,opt,name=big_order,json=bigOrder,proto3" json:"big_order,omitempty"`                                   // 大单净流入
	MiddleOrder        *NetInAmountDetail `protobuf:"bytes,10,opt,name=middle_order,json=middleOrder,proto3" json:"middle_order,omitempty"`                         // 中单净流入
	SmallOrder         *NetInAmountDetail `protobuf:"bytes,11,opt,name=small_order,json=smallOrder,proto3" json:"small_order,omitempty"`                            // 小单净流入
}

func (x *RealtimeMoneyTrendItem) Reset() {
	*x = RealtimeMoneyTrendItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goshare_others_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealtimeMoneyTrendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeMoneyTrendItem) ProtoMessage() {}

func (x *RealtimeMoneyTrendItem) ProtoReflect() protoreflect.Message {
	mi := &file_goshare_others_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeMoneyTrendItem.ProtoReflect.Descriptor instead.
func (*RealtimeMoneyTrendItem) Descriptor() ([]byte, []int) {
	return file_goshare_others_proto_rawDescGZIP(), []int{1}
}

func (x *RealtimeMoneyTrendItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RealtimeMoneyTrendItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RealtimeMoneyTrendItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RealtimeMoneyTrendItem) GetUpdownPercentage() float64 {
	if x != nil {
		return x.UpdownPercentage
	}
	return 0
}

func (x *RealtimeMoneyTrendItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RealtimeMoneyTrendItem) GetSuperSuperBigOrder() *NetInAmountDetail {
	if x != nil {
		return x.SuperSuperBigOrder
	}
	return nil
}

func (x *RealtimeMoneyTrendItem) GetSuperBigOrder() *NetInAmountDetail {
	if x != nil {
		return x.SuperBigOrder
	}
	return nil
}

func (x *RealtimeMoneyTrendItem) GetBigOrder() *NetInAmountDetail {
	if x != nil {
		return x.BigOrder
	}
	return nil
}

func (x *RealtimeMoneyTrendItem) GetMiddleOrder() *NetInAmountDetail {
	if x != nil {
		return x.MiddleOrder
	}
	return nil
}

func (x *RealtimeMoneyTrendItem) GetSmallOrder() *NetInAmountDetail {
	if x != nil {
		return x.SmallOrder
	}
	return nil
}

type RealtimeMoneyTrendItemList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*RealtimeMoneyTrendItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RealtimeMoneyTrendItemList) Reset() {
	*x = RealtimeMoneyTrendItemList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goshare_others_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealtimeMoneyTrendItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeMoneyTrendItemList) ProtoMessage() {}

func (x *RealtimeMoneyTrendItemList) ProtoReflect() protoreflect.Message {
	mi := &file_goshare_others_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeMoneyTrendItemList.ProtoReflect.Descriptor instead.
func (*RealtimeMoneyTrendItemList) Descriptor() ([]byte, []int) {
	return file_goshare_others_proto_rawDescGZIP(), []int{2}
}

func (x *RealtimeMoneyTrendItemList) GetList() []*RealtimeMoneyTrendItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_goshare_others_proto protoreflect.FileDescriptor

var file_goshare_others_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x6f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x6f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22,
	0x4b, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x49, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x22, 0xe3, 0x03, 0x0a,
	0x16, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x54, 0x72,
	0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x70, 0x64,
	0x6f, 0x77, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x75, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x4d, 0x0a, 0x15, 0x73, 0x75,
	0x70, 0x65, 0x72, 0x5f, 0x73, 0x75, 0x70, 0x65, 0x72, 0x5f, 0x62, 0x69, 0x67, 0x5f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x49, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x12, 0x73, 0x75, 0x70, 0x65, 0x72, 0x53, 0x75, 0x70, 0x65,
	0x72, 0x42, 0x69, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0f, 0x73, 0x75, 0x70,
	0x65, 0x72, 0x5f, 0x62, 0x69, 0x67, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x4e, 0x65, 0x74,
	0x49, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0d,
	0x73, 0x75, 0x70, 0x65, 0x72, 0x42, 0x69, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x37, 0x0a,
	0x09, 0x62, 0x69, 0x67, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x49, 0x6e,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x62, 0x69,
	0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0c, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x49, 0x6e, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0b, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0b, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x49, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0a, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0x51, 0x0a, 0x1a, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x33, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x67, 0x6f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x6d, 0x65, 0x73, 0x73, 0x68, 0x65, 0x6e, 0x6a, 0x69, 0x61,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x6f, 0x2f,
	0x67, 0x6f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goshare_others_proto_rawDescOnce sync.Once
	file_goshare_others_proto_rawDescData = file_goshare_others_proto_rawDesc
)

func file_goshare_others_proto_rawDescGZIP() []byte {
	file_goshare_others_proto_rawDescOnce.Do(func() {
		file_goshare_others_proto_rawDescData = protoimpl.X.CompressGZIP(file_goshare_others_proto_rawDescData)
	})
	return file_goshare_others_proto_rawDescData
}

var file_goshare_others_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_goshare_others_proto_goTypes = []interface{}{
	(*NetInAmountDetail)(nil),          // 0: goshare.NetInAmountDetail
	(*RealtimeMoneyTrendItem)(nil),     // 1: goshare.RealtimeMoneyTrendItem
	(*RealtimeMoneyTrendItemList)(nil), // 2: goshare.RealtimeMoneyTrendItemList
}
var file_goshare_others_proto_depIdxs = []int32{
	0, // 0: goshare.RealtimeMoneyTrendItem.super_super_big_order:type_name -> goshare.NetInAmountDetail
	0, // 1: goshare.RealtimeMoneyTrendItem.super_big_order:type_name -> goshare.NetInAmountDetail
	0, // 2: goshare.RealtimeMoneyTrendItem.big_order:type_name -> goshare.NetInAmountDetail
	0, // 3: goshare.RealtimeMoneyTrendItem.middle_order:type_name -> goshare.NetInAmountDetail
	0, // 4: goshare.RealtimeMoneyTrendItem.small_order:type_name -> goshare.NetInAmountDetail
	1, // 5: goshare.RealtimeMoneyTrendItemList.list:type_name -> goshare.RealtimeMoneyTrendItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_goshare_others_proto_init() }
func file_goshare_others_proto_init() {
	if File_goshare_others_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goshare_others_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetInAmountDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goshare_others_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealtimeMoneyTrendItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goshare_others_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealtimeMoneyTrendItemList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goshare_others_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goshare_others_proto_goTypes,
		DependencyIndexes: file_goshare_others_proto_depIdxs,
		MessageInfos:      file_goshare_others_proto_msgTypes,
	}.Build()
	File_goshare_others_proto = out.File
	file_goshare_others_proto_rawDesc = nil
	file_goshare_others_proto_goTypes = nil
	file_goshare_others_proto_depIdxs = nil
}
